[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.11"

[features]
resolution = true
skip-lint = false

[programs.localnet]
# liquidity_incentive_program = "Lip1111111111111111111111111111111111111111"
marginfi = "2jGhuVUuy3umdzByFx8sNWUAaf5vaeuDm78RDPEnhrMr"
mocks = "5XaaR94jBubdbrRrNW7DtRvZeWvLhSHkEGU3jHTEXV3C"
spl_single_pool = "SVSPxpvHdN29nkVg9rPapPNDddN5DipNLRUFhyjFThE"  # cloned from solana-labs repo (see below)
kamino_lending = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD" # cloned from Kamino repo (see below)

[programs.mainnet]
liquidity_incentive_program = "LipsxuAkFkwa4RKNzn51wAsW7Dedzt1RNHMkTkDEZUW"
marginfi = "MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

# (remove RUST_LOG= to see bankRun logs)
[scripts]
# test = "RUST_LOG= yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.spec.ts --exit --require tests/rootHooks.ts"

# Staked collateral tests only
# test = "RUST_LOG= yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/s*.spec.ts --exit --require tests/rootHooks.ts"

# Kamino tests only
test = "RUST_LOG= yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/k*.spec.ts --exit --require tests/rootHooks.ts"

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "DeyH7QxWvnbbaVB4zFrf4hoq7Q8z1ZT14co42BGwGtfM"
filename = "tests/fixtures/bonk_bank.json"

[[test.validator.account]]
address = "4kNXetv8hSv9PzvzPZzEs1CTH6ARRRi2b8h6jk1ad1nP"
filename = "tests/fixtures/cloud_bank.json"

[[test.validator.account]]
address = "Fe5QkKPVAh629UPP5aJ8sDZu8HTfe6M26jDQkKyXVhoA"
filename = "tests/fixtures/pyusd_bank.json"

[[test.validator.account]]
address = "8FRFC6MoGGkMFQwngccyu69VnYbzykGeez7ignHVAFSN"
filename = "tests/fixtures/localnet_usdc.json"

# To update:
# clone https://github.com/solana-labs/solana-program-library/tree/master and run cargo build-sbf in spl_single_pool
[[test.genesis]]
address = "SVSPxpvHdN29nkVg9rPapPNDddN5DipNLRUFhyjFThE" # spl single pool program
program = "tests/fixtures/spl_single_pool.so"

# To update:
# * clone https://github.com/Kamino-Finance/klend and run anchor build
# * copy the .so file to fixtures. 
# If Kamino is still using Anchor version <0.30.1, do the following steps too:
# * copy the .json idl to another folder (for example your desktop) and run 
# anchor idl convert kamino_lending.json -o converted_idl.json
# * delete the old file, rename convert_idl to kamino_lending.json, and run
# anchor idl type kamino_lending.json -o kamino_lending.ts
# * copy both files to fixtures
[[test.genesis]]
address = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD" # klend program
program = "tests/fixtures/kamino_lending.so"