[workspace]
resolver = "2"
members = [
  "programs/marginfi/fuzz/pyth-layout-test",
  "programs/*",
  "clients/rust/*",
  "tools/*",
  #"observability/indexer"
]
exclude = ["programs/brick"]

[workspace.dependencies]
solana-cli-output = "1.18.5"
solana-client = "1.18.5"
solana-sdk = "1.18.5"
solana-logger = "1.18.5"
solana-program = "1.18.5"
solana-program-test = "1.18.5"
solana-account-decoder = "1.18.5"
solana-measure = "1.18.5"
solana-metrics = "1.18.5"
solana-transaction-status = "1.18.5"
spl-token = "4.0.0"
spl-token-2022 = { git = "https://github.com/solana-labs/solana-program-library", rev = "20e6792179fc7f1251579c1c33a4a0feec48e15e" }
spl-associated-token-account = "2.2.0"

anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token_2022"] }
anchor-client = "0.30.1"

switchboard-solana = "0.29.0"
pyth-sdk-solana = "0.9.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
