[workspace]
resolver = "2"
members = [
    "programs/*",
    "clients/rust/*",
    "tools/*",
    #"observability/indexer"
]
exclude = ["programs/brick"]

[workspace.dependencies]
solana-cli-output = "1.18.2"
solana-client = "1.18.2"
solana-sdk = "1.18.2"
solana-logger = "1.18.2"
solana-program = "1.18.2"
solana-program-test = "1.18.2"
solana-account-decoder = "1.18.2"
solana-measure = "1.18.2"
solana-metrics = "1.18.2"
solana-transaction-status = "1.18.2"
spl-token = "4.0.0"
spl-associated-token-account = "2.2.0"

anchor-lang = "0.30.0"
anchor-spl = { version = "0.30.0", features = ["token_2022"] }
anchor-client = "0.30.0"

switchboard-solana = "0.29.0"
pyth-sdk-solana = "0.9.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
